## Checklist para revisar el paquete {.appendix}

A lo largo de las secciones los ejercicios transversales que llamamos "Construyendo un paquete de R paso a paso" son una guía para, justamente, construir un paquete que lee y ayuda a analizar datos meteorológicos. 

A continuación encontrarás una lista de elementos que debe tener o con los que debe cumplir el paquete para estar completo. 

- [ ] Estructura del paquete
- [ ] Repositorio local
- [ ] Repositorio remoto

## DESCRIPTION

- [ ] Título
- [ ] Descripción
- [ ] Las personas involucradas estan listadas en Auth@rs

## Funciones y datos

- [ ] (al menos) 3 funciones
- [ ] (al menos) 1 set de datos
- [ ] Las dependencias están bien definidas

## Documentación

- [ ] Todas las funciones y datos están documentados y tienen ejemplos de uso
- [ ] Incluye un README con:
  - [ ] como instalar el paquete.
  - [ ] los autores. 
  - [ ] como se puede contribuir al paquete.  
- [ ] Incluye una viñeta que explica como usar las funciones
- [ ] El paquete tiene una página web

## Tests

- [ ] El paquete tiene tests que cubren al menos el 75% del código de las funciones
- [ ] El paquete tiene una GitHub action que revisa la covertura de los tests
- [ ] El paquete pasa R CMD checks
- [ ] El paquete tiene una GitHub action que chequea el paquete en distintos sistemas operativos

## Otros

- [ ] Incluye una licencia
- [ ] Incluye un código de conducta
- [ ] El README incluye:
  - [ ] etiquetas (covertura de tests, lifecycle, etc).
  - [ ] un logo para el paquete. 

