<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.528">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Yanina Bellini Saibene y Paola Corrales">
<title>Introducción a la Programación II - 7&nbsp; Manipulación de datos ordenados II</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07_funciones.html" rel="next">
<link href="./05_graficos.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06_manipulacion-2.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Manipulación de datos ordenados II</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introducción a la Programación II</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/rse-r/intro-programacion" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Presentación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_proyectos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Entorno de trabajo</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_lectura.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lectura de datos ordenados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_manipulacion-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Manipulación de datos ordenados I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_git-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">git para trabajar individualmente</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_graficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Graficado datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_manipulacion-2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Manipulación de datos ordenados II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_funciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Funciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_git-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Git para trabajar en equipo</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_paquetes-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Empaquetando funciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_documentacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Documentando paquetes y funciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_errores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Dependencias y tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_publicacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Publicar y compartir código</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_reproducibilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Análisis de datos y reproducibilidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A_instalacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Preparando el entorno de trabajo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B_config_pk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Configuración para desarrollar paquetes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C_soluciones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Soluciones de ejercicios</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./D_checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Checklist para revisar el paquete</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#de-ancho-a-largo-con-pivot_longer" id="toc-de-ancho-a-largo-con-pivot_longer" class="nav-link active" data-scroll-target="#de-ancho-a-largo-con-pivot_longer"><span class="header-section-number">7.1</span> De ancho a largo con <code>pivot_longer()</code></a></li>
  <li><a href="#de-largo-a-ancho-con-pivot_wider" id="toc-de-largo-a-ancho-con-pivot_wider" class="nav-link" data-scroll-target="#de-largo-a-ancho-con-pivot_wider"><span class="header-section-number">7.2</span> De largo a ancho con <code>pivot_wider()</code></a></li>
  <li>
<a href="#uniendo-tablas" id="toc-uniendo-tablas" class="nav-link" data-scroll-target="#uniendo-tablas"><span class="header-section-number">7.3</span> Uniendo tablas</a>
  <ul class="collapse">
<li><a href="#ex-exploracion" id="toc-ex-exploracion" class="nav-link" data-scroll-target="#ex-exploracion"><span class="header-section-number">7.3.1</span> Construyendo un paquete de R paso a paso</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Manipulación de datos ordenados II</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Venimos hablando y trabajando con datos ordenados, o en formato largo, donde:</p>
<ul>
<li>cada fila es una observación</li>
<li>cada columna es una variable</li>
</ul>
<p>Podríamos organizar la informaciuón es un formato “ancho” donde:</p>
<ul>
<li>cada fila es un “item”</li>
<li>cada columna es una variable</li>
</ul>
<p><img src="images/largo-ancho.png" class="img-fluid"></p>
<p>Una tabla en formato largo va a tener una cierta cantidad de columnas que cumplen el rol de <em>identificadores </em> y cuya combinación identifican una única observación y una única columna con el valor de la observación. En el ejemplo de arriba, <code>pais</code> y <code>anio</code> son las columnas identificadoras y <code>casos</code> es la columna que contiene el valor de las observaciones.</p>
<p>En una tabla ancha, cada observación única se identifica a partir de la intersección de filas y columnas. En el ejemplo, los países están en las filas y los años en las columnas.</p>
<p>En general, el formato ancho es más compacto y legible por humanos mientras que el largo es más fácil de manejar con la computadora. Si te fijás en las tablas de arriba, es más fácil comparar los valores entre países y entre años en la tabla ancha. Pero el nombre de las columnas (“1999”, “2000”) en realidad ¡son datos! Además este formato se empieza a complicar en cuanto hay más de dos identificadores.</p>
<p>Un mismo set de datos puede ser representado de forma completamente “larga”, completamente “ancha” o –lo que es más común– en un formato intermedio pero no existe una forma “correcta” de organizar los datos; cada una tiene sus ventajas y desventajas. Por esto es que es muy normal que durante un análisis los datos vayan y vuelvan entre distintos formatos dependiendo de los métodos estadísticos que se le aplican. Entonces, aprender a transformar datos anchos en largos y viceversa es un habilidad muy útil.</p>
<div class="ejercicio">
<p>En las tablas de ejemplo cada país tiene el un valor observado de “casos” para cada año. ¿Cómo agregarías una nueva variable con información sobre “precios”? Dibujá un esquema en papel y lápiz en formato ancho y uno en formato largo. ¿En qué formato es más “natural” esa extensión?</p>
</div>
<p>En esta sección vamos a usar el paquete <code>tidyr</code> para manipular datos. Si no lo tenés instalado, instalalo con el comando:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"tidyr"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(como siempre, recordá que esto hay que hacerlo una única vez en la consola)</p>
<p>Y luego cargá tidyr y dplyr con:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<section id="de-ancho-a-largo-con-pivot_longer" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="de-ancho-a-largo-con-pivot_longer">
<span class="header-section-number">7.1</span> De ancho a largo con <code>pivot_longer()</code>
</h2>
<p>Antes, usamos el set de datos de paises que viene en el paquete datos. Vamos a usar los datos originales que tienen un formato ancho.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_ancho</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/paises_ancho.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 142 Columns: 38
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): pais, continente
dbl (36): esperanza_de_vida-1952, esperanza_de_vida-1957, esperanza_de_vida-...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_ancho</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 38
   pais       continente `esperanza_de_vida-1952` `esperanza_de_vida-1957`
   &lt;chr&gt;      &lt;chr&gt;                         &lt;dbl&gt;                    &lt;dbl&gt;
 1 Afganistán Asia                           28.8                     30.3
 2 Albania    Europa                         55.2                     59.3
 3 Argelia    África                         43.1                     45.7
 4 Angola     África                         30.0                     32.0
 5 Argentina  Américas                       62.5                     64.4
 6 Australia  Oceanía                        69.1                     70.3
 7 Austria    Europa                         66.8                     67.5
 8 Baréin     Asia                           50.9                     53.8
 9 Bangladesh Asia                           37.5                     39.3
10 Bélgica    Europa                         68                       69.2
# ℹ 132 more rows
# ℹ 34 more variables: `esperanza_de_vida-1962` &lt;dbl&gt;,
#   `esperanza_de_vida-1967` &lt;dbl&gt;, `esperanza_de_vida-1972` &lt;dbl&gt;,
#   `esperanza_de_vida-1977` &lt;dbl&gt;, `esperanza_de_vida-1982` &lt;dbl&gt;,
#   `esperanza_de_vida-1987` &lt;dbl&gt;, `esperanza_de_vida-1992` &lt;dbl&gt;,
#   `esperanza_de_vida-1997` &lt;dbl&gt;, `esperanza_de_vida-2002` &lt;dbl&gt;,
#   `esperanza_de_vida-2007` &lt;dbl&gt;, `poblacion-1952` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<div class="importante">
<p>¿Notaste que en el código anterior no usaste <code><a href="https://readr.tidyverse.org">library(readr)</a></code> para cargar el paquete y luego leer? Con la notación <code>paquete::funcion()</code> podés acceder a las funciones de un paquete sin tener que cargarlo. Es una buena forma de no tener que cargar un montón de paquetes innecesarios si vas a correr una única función de un paquete pocas veces.</p>
</div>
<p>Esta tabla, increíblemente ancha, es muy difícil de manejar. Por ejemplo, es imposible hacer una serie de tiempo de una variable, o calcular el promedio por variable y país; ni hablar de calcular una regresión lineal.</p>
<p>Para convertirlo en una tabla más larga, se usa <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code> (“longer” es “más largo” en inglés):</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_largo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span><span class="va">paises_ancho</span>,</span>
<span>                             cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">'pob'</span><span class="op">)</span>, </span>
<span>                                      <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">'esperanza'</span><span class="op">)</span>, </span>
<span>                                      <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">'pib_per'</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                             names_to <span class="op">=</span> <span class="st">"variable_anio"</span>, </span>
<span>                             values_to <span class="op">=</span> <span class="st">"valor"</span></span>
<span><span class="op">)</span></span>
<span><span class="va">paises_largo</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,112 × 4
   pais       continente variable_anio     valor
   &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;             &lt;dbl&gt;
 1 Afganistán Asia       poblacion-1952  8425333
 2 Afganistán Asia       poblacion-1957  9240934
 3 Afganistán Asia       poblacion-1962 10267083
 4 Afganistán Asia       poblacion-1967 11537966
 5 Afganistán Asia       poblacion-1972 13079460
 6 Afganistán Asia       poblacion-1977 14880372
 7 Afganistán Asia       poblacion-1982 12881816
 8 Afganistán Asia       poblacion-1987 13867957
 9 Afganistán Asia       poblacion-1992 16317921
10 Afganistán Asia       poblacion-1997 22227415
# ℹ 5,102 more rows</code></pre>
</div>
</div>
<p>El primer argumento de<code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code> es la tabla que va a modificar: <code>paises_ancho</code>. El segundo argumento se llama <code>cols</code> y es un vector con las columnas que tienen los valores a “alargar”. Podría ser un vector escrito a mano (algo como <code>c("pib_per_capita-1952", "pib_per_capita-1957"...)</code>) pero con más de 30 columnas, escribir todo eso sería tedioso y probablemente estaría lleno de errores. Por eso tidyr provee funciones de ayuda para seleccionar columnas en base a patrones. El código de arriba usa <code><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with()</a></code> que, como su nombre en inglés lo indica, selecciona las columnas que <em>empiezan con</em> una determinada cadena de caracteres. El vector <code>c(starts_with('pob'), starts_with('esperanza'), starts_with('pib_per'))</code> le dice a <code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code> que seleccione las columnas que empieza con “pob”, las que empiezan con “esperanza” y las que empiezan con “pib_per”.</p>
<div class="importante">
<p>Estas funciones accesorias para seleccionar muchas funciones se llaman “tidyselect”. Si querés leer más detalles de las distintas formas que podés seleccionar variables leé la documentación usando <code><a href="https://tidyselect.r-lib.org/reference/language.html">?tidyselect::language</a></code>.</p>
</div>
<p>El tercer y cuarto argumento son los nombres de las columnas de “nombre” y de “valor” que va a tener la nueva tabla. Como la nueva columna de identificación tiene los datos de la variable y el año a medir, “variable_anio” es un buen nombre. Y la columna de valor va a tener… bueno, el valor.</p>
<p>Tomate un momento para visualizar lo que acaba de pasar. La tabla ancha tenía un montón de columnas con distintos datos. Ahora estos datos están uno arriba de otro en la columna “valor”, pero para identificar el nombre de la columna de la cual vinieron, se agrega la columna “variable_anio”.</p>
<div class="img-fluid quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/ancho-a-largo.png" class="img-fluid figure-img"></p>
<figcaption>Proceso de largo a ancho</figcaption></figure>
</div>
<p>La columna <code>variable_anio</code> todavía no es muy útil porque contiene 2 datos, la variable (población, expectativa de vida o PBI per cápita) y el año. Sería mejor separar esta información en dos columnas llamadas “variable” y “anio”. Para eso está la función <code><a href="https://tidyr.tidyverse.org/reference/separate.html">separate()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_largo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/separate_wider_delim.html">separate_wider_delim</a></span><span class="op">(</span><span class="va">paises_largo</span>, </span>
<span>         col <span class="op">=</span> <span class="va">variable_anio</span>, </span>
<span>         delim <span class="op">=</span> <span class="st">"-"</span>,</span>
<span>         names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"variable"</span>, <span class="st">"anio"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">paises_largo</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,112 × 5
   pais       continente variable  anio     valor
   &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;
 1 Afganistán Asia       poblacion 1952   8425333
 2 Afganistán Asia       poblacion 1957   9240934
 3 Afganistán Asia       poblacion 1962  10267083
 4 Afganistán Asia       poblacion 1967  11537966
 5 Afganistán Asia       poblacion 1972  13079460
 6 Afganistán Asia       poblacion 1977  14880372
 7 Afganistán Asia       poblacion 1982  12881816
 8 Afganistán Asia       poblacion 1987  13867957
 9 Afganistán Asia       poblacion 1992  16317921
10 Afganistán Asia       poblacion 1997  22227415
# ℹ 5,102 more rows</code></pre>
</div>
</div>
<p>El primer argumento, como siempre, es la tabla a procesar. El segundo, <code>col</code>, es la columna a separar en dos (o más) columnas nuevas. El segundo argumento indica cómo se separan los elementos, en este caso con guíon “-”. El tercero, <code>names</code> es el nombre de las nuevas columnas que <code><a href="https://tidyr.tidyverse.org/reference/separate_wider_delim.html">separate_wider_delim()</a></code> va a crear.</p>
<p>Y ya casi. Pero fijate que debajo de la columna <code>anio</code> dice <code>&lt;chr&gt;</code>; eso significa que el tipo de la columna es caracter, pero los años son números. Usando <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> podemos convertir la columna <code>anio</code> a entero usando <code><a href="https://rdrr.io/r/base/integer.html">as.integer()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_largo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">paises_largo</span>, </span>
<span>                       anio <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="va">anio</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">paises_largo</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5,112 × 5
   pais       continente variable   anio    valor
   &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;     &lt;int&gt;    &lt;dbl&gt;
 1 Afganistán Asia       poblacion  1952  8425333
 2 Afganistán Asia       poblacion  1957  9240934
 3 Afganistán Asia       poblacion  1962 10267083
 4 Afganistán Asia       poblacion  1967 11537966
 5 Afganistán Asia       poblacion  1972 13079460
 6 Afganistán Asia       poblacion  1977 14880372
 7 Afganistán Asia       poblacion  1982 12881816
 8 Afganistán Asia       poblacion  1987 13867957
 9 Afganistán Asia       poblacion  1992 16317921
10 Afganistán Asia       poblacion  1997 22227415
# ℹ 5,102 more rows</code></pre>
</div>
</div>
<div class="ejercicio">
<p>Juntá todos los pasos anteriores en una sola cadena de operaciones usando <code>|&gt;</code>.</p>
</div>
</section><section id="de-largo-a-ancho-con-pivot_wider" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="de-largo-a-ancho-con-pivot_wider">
<span class="header-section-number">7.2</span> De largo a ancho con <code>pivot_wider()</code>
</h2>
<p>Ahora la variable <code>paises_largo</code> está en el formato más largo posible. Tiene 5 columnas, de las cuales sólo una es la columnas con valores. Pero con los datos así no podrías hacer un gráfico de puntos que muestre la relación entre el PBI per cápita y la expectativa de vida como en la <a href="06_graficos.html">sección de gráficos</a>. Fijate que los valores de la columna <code>valor</code> no tienen todos las mismas unidades, por lo que operar con ese vector podría dar resultados sin sentido. Muchas veces es conveniente y natural tener los datos en un formato intermedio en donde hay múltiples columnas con los valores de distintas variables observadas.</p>
<p>Pasa “ensanchar” una tabla está la función <code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider()</a></code> (“wider” es “más ancha” en inglés) y el código para conseguir este formato intermedio es:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_medio</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span><span class="va">paises_largo</span>, names_from <span class="op">=</span> <span class="va">variable</span>, values_from <span class="op">=</span> <span class="va">valor</span><span class="op">)</span></span>
<span><span class="va">paises_medio</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,704 × 6
   pais       continente  anio poblacion esperanza_de_vida pib_per_capita
   &lt;chr&gt;      &lt;chr&gt;      &lt;int&gt;     &lt;dbl&gt;             &lt;dbl&gt;          &lt;dbl&gt;
 1 Afganistán Asia        1952   8425333              28.8           779.
 2 Afganistán Asia        1957   9240934              30.3           821.
 3 Afganistán Asia        1962  10267083              32.0           853.
 4 Afganistán Asia        1967  11537966              34.0           836.
 5 Afganistán Asia        1972  13079460              36.1           740.
 6 Afganistán Asia        1977  14880372              38.4           786.
 7 Afganistán Asia        1982  12881816              39.9           978.
 8 Afganistán Asia        1987  13867957              40.8           852.
 9 Afganistán Asia        1992  16317921              41.7           649.
10 Afganistán Asia        1997  22227415              41.8           635.
# ℹ 1,694 more rows</code></pre>
</div>
</div>
<p>Nuevamente el primer argumento es la tabla original. El segundo, <code>names_from</code> es la columna cuyos valores únicos van a convertirse en nuevas columnas. La columna <code>variable</code> tiene los valores <code>"población"</code>, <code>"esperanza_de_vida"</code> y <code>"pib_per_capita"</code> y entonces la tabla nueva tendrá tres columnas con esos nombres. El tercer argumento, <code>values_from</code>, es la columna de la cual sacar los valores.</p>
<p>Para volver al formato más ancho, basta con agregar más columnas en el argumento <code>names_from</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span><span class="va">paises_largo</span>, </span>
<span>            names_from <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">variable</span>, <span class="va">anio</span><span class="op">)</span>, </span>
<span>            names_sep <span class="op">=</span> <span class="st">"-"</span>,</span>
<span>            values_from <span class="op">=</span> <span class="va">valor</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 38
   pais       continente `poblacion-1952` `poblacion-1957` `poblacion-1962`
   &lt;chr&gt;      &lt;chr&gt;                 &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
 1 Afganistán Asia                8425333          9240934         10267083
 2 Albania    Europa              1282697          1476505          1728137
 3 Argelia    África              9279525         10270856         11000948
 4 Angola     África              4232095          4561361          4826015
 5 Argentina  Américas           17876956         19610538         21283783
 6 Australia  Oceanía             8691212          9712569         10794968
 7 Austria    Europa              6927772          6965860          7129864
 8 Baréin     Asia                 120447           138655           171863
 9 Bangladesh Asia               46886859         51365468         56839289
10 Bélgica    Europa              8730405          8989111          9218400
# ℹ 132 more rows
# ℹ 33 more variables: `poblacion-1967` &lt;dbl&gt;, `poblacion-1972` &lt;dbl&gt;,
#   `poblacion-1977` &lt;dbl&gt;, `poblacion-1982` &lt;dbl&gt;, `poblacion-1987` &lt;dbl&gt;,
#   `poblacion-1992` &lt;dbl&gt;, `poblacion-1997` &lt;dbl&gt;, `poblacion-2002` &lt;dbl&gt;,
#   `poblacion-2007` &lt;dbl&gt;, `esperanza_de_vida-1952` &lt;dbl&gt;,
#   `esperanza_de_vida-1957` &lt;dbl&gt;, `esperanza_de_vida-1962` &lt;dbl&gt;,
#   `esperanza_de_vida-1967` &lt;dbl&gt;, `esperanza_de_vida-1972` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>En esta llamada también está el argumento <code>names_sep</code>, que determina el caracter que se usa para crear el nombre de las nuevas columnas.</p>
<div class="ejercicio">
<ul>
<li><p>Creá una nueva tabla, llamada <code>paises_superduper_ancho</code> que tenga una columna para cada variable, anio y país. (Consejo: la tabla final tiene que tener 5 filas).</p></li>
<li><p>¿Cómo es la tabla más ancha posible que podés generar con estos datos? ¿Cuántas filas y columnas tiene?</p></li>
</ul>
</div>
</section><section id="uniendo-tablas" class="level2" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="uniendo-tablas">
<span class="header-section-number">7.3</span> Uniendo tablas</h2>
<p>Hasta ahora todo lo que usaste de dplyr involucra trabajar y modificar con una sola tabla a la vez, pero es muy común tener dos o más tablas con datos relacionados. En ese caso, tenemos que <em>unir</em> estas tablas. a partir de una o más variables en común o <em>keys</em>. En el mundo de dplyr hay que usar la familia de funciones <code>*_join()</code>. Hay una función cada tipo de unión que queramos hacer.</p>
<p>Asumiendo que querés unir dos data.frames o tablas <code>x</code> e <code>y</code> que tienen en común una variable <code>A</code>:</p>
<p><img src="images/join.png" class="img-fluid"></p>
<ul>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join()</a></code>: devuelve todas las filas y todas las columnas de ambas tablas <code>x</code> e <code>y</code>. Cuando no coinciden los elementos en <code>x</code> o <code>y</code>, devuelve <code>NA</code> (dato faltante). Esto significa que no se pierden filas de ninguna de las dos tablas aún cuando no hay coincidencia. Está es la manera más segura de unir tablas, para no perder datos.</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code>: devuelve todas las filas de <code>x</code> y todas las columnas de <code>x</code> e <code>y</code>. Las filas en <code>x</code> que no tengan coincidencia con <code>y</code> tendrán <code>NA</code> en las nuevas columnas. Si hay múltiples coincidencias entre <code>x</code>e <code>y</code>, devuelve todas las coincidencias posibles.</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">right_join()</a></code>: es igual que <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> pero intercambiando el orden de <code>x</code> e <code>y</code>. En otras palabras, <code>right_join(x, y)</code> es idéntico a <code>left_join(y, x)</code>.</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join()</a></code>: devuelve todas las filas de <code>x</code> donde hay coincidencias con <code>y</code> y todas las columnas de <code>x</code> e <code>y</code>. Si hay múltiples coincidencias entre <code>x</code> e <code>y</code>, entonces devuelve todas las coincidencias. Esto significa que eliminará las filas (observaciones) que no coincidan en ambas tablas, lo que puede ser peligroso.</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code>: devuelve todas las filas de <code>x</code> que no tienen coincidencias con <code>y</code>. Identifica observaciones no coincidentes entre dos conjunto de datos. Es muy util para encontrar datos faltantes o para eliminar datos duplicados.</p></li>
</ul>
<p><img src="images/join_family.png" class="img-fluid"></p>
<p>Ahora vamos a seguir trabajando con las base de datos de <code>paises</code> pero nos vamos a quedar solo con las observaciones del 2007 y de paso unirlo a una nueva base de datos <code>co2</code> que contiene información de la emisión de dióxido de carbono de cada país para ese mismo año.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_2007</span> <span class="op">&lt;-</span> <span class="fu">datos</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/datos/man/paises.html">paises</a></span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">anio</span> <span class="op">==</span> <span class="fl">2007</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">co2_2007</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/co2_2007.csv"</span><span class="op">)</span></span>
<span><span class="va">co2_2007</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 218 × 3
   codigo_iso emision_co2 pais                  
   &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;                 
 1 ABW            27.9    Aruba                 
 2 AFG             0.0854 Afghanistán           
 3 AGO             1.20   Angola                
 4 ALB             1.32   Albania               
 5 AND             6.52   Andorra               
 6 ARB             4.10   Mundo Árabe           
 7 ARE            22.4    Emiratos Árabes Unidos
 8 ARG             4.38   Argentina             
 9 ARM             1.73   Armenia               
10 ATG             5.14   Antigua y Barbuda     
# ℹ 208 more rows</code></pre>
</div>
</div>
<p>Esta nueva tabla tiene 3 columnas: <code>codigo_iso</code> tiene el código ISO de 3 letras de (abreviaturas que se usan internacionalmente), <code>emision_co2</code> tiene las emisiones anuales per cápita de CO2 en toneladas, <code>pais</code> tiene el nombre del país. Esta última columna también está presente en la tabla <code>paises_2007</code> y es la que va a servir como variable llave para unir las dos tablas.</p>
<p>Para unir las dos tablas, cualquier función <em>join</em> requiere cierta información:</p>
<ul>
<li>las tablas a unir: son los dos primeros argumentos.</li>
<li>qué variable o variables (se puede usar más de una!) usar para identificar coincidencias: el argumento <code>by</code>.</li>
</ul>
<p>Unamos <code>paises_2007</code> y <code>co2_2007</code> primero con <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_co2_2007</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join</a></span><span class="op">(</span><span class="va">paises_2007</span>, <span class="va">co2_2007</span>, by <span class="op">=</span> <span class="st">"pais"</span><span class="op">)</span></span>
<span><span class="va">paises_co2_2007</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 241 × 8
   pais   continente  anio esperanza_de_vida poblacion pib_per_capita codigo_iso
   &lt;chr&gt;  &lt;fct&gt;      &lt;int&gt;             &lt;dbl&gt;     &lt;int&gt;          &lt;dbl&gt; &lt;chr&gt;     
 1 Afgan… Asia        2007              43.8  31889923           975. &lt;NA&gt;      
 2 Alban… Europa      2007              76.4   3600523          5937. ALB       
 3 Argel… África      2007              72.3  33333216          6223. &lt;NA&gt;      
 4 Angola África      2007              42.7  12420476          4797. AGO       
 5 Argen… Américas    2007              75.3  40301927         12779. ARG       
 6 Austr… Oceanía     2007              81.2  20434176         34435. AUS       
 7 Austr… Europa      2007              79.8   8199783         36126. AUT       
 8 Baréin Asia        2007              75.6    708573         29796. &lt;NA&gt;      
 9 Bangl… Asia        2007              64.1 150448339          1391. BGD       
10 Bélgi… Europa      2007              79.4  10392226         33693. BEL       
# ℹ 231 more rows
# ℹ 1 more variable: emision_co2 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Si miramos de cerca la tabla unida veremos un par de cosas:</p>
<ul>
<li>Todas las columnas de <code>paises_2007</code> y de <code>co2_2007</code> están presentes.</li>
<li>Todas las observaciones están presentes, aún los países que están presentes en <code>co2_2007</code> pero no en <code>paises_2007</code> y viceversa. En esos casos ahora tenemos <code>NA</code>. Esto genera una tabla con 241 filas.</li>
</ul>
<p>Esta es la opción más segura si no sabemos si todas las observaciones de una tabla están presente en a otra.</p>
<p>Si solo nos interesa conservar las filas de la tabla <em>de la izquierda</em>, en este caso <code>paises_2007</code> entonces:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_co2_2007</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">paises_2007</span>, <span class="va">co2_2007</span>, by <span class="op">=</span> <span class="st">"pais"</span><span class="op">)</span></span>
<span><span class="va">paises_co2_2007</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 142 × 8
   pais   continente  anio esperanza_de_vida poblacion pib_per_capita codigo_iso
   &lt;chr&gt;  &lt;fct&gt;      &lt;int&gt;             &lt;dbl&gt;     &lt;int&gt;          &lt;dbl&gt; &lt;chr&gt;     
 1 Afgan… Asia        2007              43.8  31889923           975. &lt;NA&gt;      
 2 Alban… Europa      2007              76.4   3600523          5937. ALB       
 3 Argel… África      2007              72.3  33333216          6223. &lt;NA&gt;      
 4 Angola África      2007              42.7  12420476          4797. AGO       
 5 Argen… Américas    2007              75.3  40301927         12779. ARG       
 6 Austr… Oceanía     2007              81.2  20434176         34435. AUS       
 7 Austr… Europa      2007              79.8   8199783         36126. AUT       
 8 Baréin Asia        2007              75.6    708573         29796. &lt;NA&gt;      
 9 Bangl… Asia        2007              64.1 150448339          1391. BGD       
10 Bélgi… Europa      2007              79.4  10392226         33693. BEL       
# ℹ 132 more rows
# ℹ 1 more variable: emision_co2 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Ahora esperamos que la tabla resultante tenga la misma cantidad de filas que <code>paises_2007</code> y efectivamente eso ocurre. Pero al mismo tiempo varios países en esa tabla no encontraron coincidencia en <code>co2_2007</code> y por esa razón, la columna nueva columna <code>emisiones_co2</code> tiene <code>NA</code>.</p>
<p>Si quisiéramos quedarnos <em>solo</em> con las observaciones que están presentes en ambas tablas usamos <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">paises_co2_2007</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join</a></span><span class="op">(</span><span class="va">paises_2007</span>, <span class="va">co2_2007</span>, by <span class="op">=</span> <span class="st">"pais"</span><span class="op">)</span></span>
<span><span class="va">paises_co2_2007</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 119 × 8
   pais   continente  anio esperanza_de_vida poblacion pib_per_capita codigo_iso
   &lt;chr&gt;  &lt;fct&gt;      &lt;int&gt;             &lt;dbl&gt;     &lt;int&gt;          &lt;dbl&gt; &lt;chr&gt;     
 1 Alban… Europa      2007              76.4   3600523          5937. ALB       
 2 Angola África      2007              42.7  12420476          4797. AGO       
 3 Argen… Américas    2007              75.3  40301927         12779. ARG       
 4 Austr… Oceanía     2007              81.2  20434176         34435. AUS       
 5 Austr… Europa      2007              79.8   8199783         36126. AUT       
 6 Bangl… Asia        2007              64.1 150448339          1391. BGD       
 7 Bélgi… Europa      2007              79.4  10392226         33693. BEL       
 8 Boliv… Américas    2007              65.6   9119152          3822. BOL       
 9 Bosni… Europa      2007              74.9   4552198          7446. BIH       
10 Botsw… África      2007              50.7   1639131         12570. BWA       
# ℹ 109 more rows
# ℹ 1 more variable: emision_co2 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>En este caso, perdemos las filas de <code>co2_2007</code> que no encontraron coincidencia en <code>paises_2007</code> y viceversa y la tabla resultante tiene aún menos filas (119).</p>
<p>Finalmente, si quisieramos quedarnos con los paises para los cuales no tenemos datos de co2, o sea las observaciones en <code>paises_2007</code> que no tienen coincidencia en <code>co2_2007</code> usamos <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sin_co2_2007</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">paises_2007</span>, <span class="va">co2_2007</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(pais)`</code></pre>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sin_co2_2007</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 6
   pais              continente  anio esperanza_de_vida poblacion pib_per_capita
   &lt;fct&gt;             &lt;fct&gt;      &lt;int&gt;             &lt;dbl&gt;     &lt;int&gt;          &lt;dbl&gt;
 1 Afganistán        Asia        2007              43.8  31889923           975.
 2 Argelia           África      2007              72.3  33333216          6223.
 3 Baréin            Asia        2007              75.6    708573         29796.
 4 Benin             África      2007              56.7   8078314          1441.
 5 Camboya           Asia        2007              59.7  14131858          1714.
 6 República Centro… África      2007              44.7   4369038           706.
 7 Comoras           África      2007              65.2    710960           986.
 8 Congo             África      2007              55.3   3800610          3633.
 9 Yibuti            África      2007              54.8    496374          2082.
10 Guinea Bissau     África      2007              46.4   1472041           579.
# ℹ 13 more rows</code></pre>
</div>
</div>
<div class="ejercicio">
<p>Estuvimos trabajando con una parte de la base de datos de emisiones. Pero también está disponible <code>co2_completo.csv</code> que contiene las emisiones para distintos años. El objetivo es que unas <code>paises</code> y <code>co2</code> teniendo en cuenta tanto el país como el año. Para eso:</p>
<ol type="1">
<li>Lee la base de datos <code>co2_completo.csv</code> en una nueva variable que se llame <code>co2</code>.</li>
<li>Revisá el nombre de las variables en esta base de datos, ¿se llaman igual que las variables en <code>paises</code>?</li>
<li>Uní las dos tablas usando <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join()</a></code>, tené en cuenta que ahora usamos dos variables llave <code>pais</code> y <code>anio</code>. Buscá en la documentación cómo indicarle eso a la función <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">full_join()</a></code>.</li>
</ol>
<p>Podés descargar los datos desde https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/co2_completo.csv</p>
</div>
<section id="ex-exploracion" class="level3" data-number="7.3.1"><h3 data-number="7.3.1" class="anchored" data-anchor-id="ex-exploracion">
<span class="header-section-number">7.3.1</span> Construyendo un paquete de R paso a paso</h3>
<div class="ejercicios">
<p><strong>Pivots!</strong></p>
<p>Recordás el ejercicio 3 de dplyr?</p>
<blockquote class="blockquote">
<p>¿Cuál es el promedio de la temperatura de abrigo a 150 cm en cada estación? ¿Y el desvío estandar? Pista: la mayoría de las funciones tienen un argumento para <em>sacar</em> los <code>NA</code> del cálculo, revisá la documentación de <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> y de <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>.</p>
</blockquote>
<ol type="1">
<li>Usando las funciones <code>pivot_</code> alargá el resultado anterior de tal manera que queden los valores de temperatura máxima y mínima en la misma columna.</li>
<li>A continuación <strong>usando el resultado anterior</strong> volvé a ensanchar la tabla de tal manera que tengas columnas con los nombres de las estaciones y en las filas los valores de la media y el desvio estandar.</li>
</ol>
<p><strong>uniones</strong></p>
<p>A la hora de analizar datos meteorológicos, tener en cuenta la ubicación y altitud de las estaciones donde se toman las mediciones es muy importane. Sin embargo eso no está incluido en los datos con los que venimos trabajando.</p>
<p>Esta información son <strong>metadatos</strong> y suelen venir por separado (si tenemos suerte!). En este caso los tenemos y están disponibles en <a href="https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/metadatos_completos.csv">https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/metadatos_completos.csv</a>.</p>
<ol type="1">
<li>Lee los metadatos</li>
<li>Identifica cuales son las variables clave, aquellas que son comunes entre los datos meteorológicos con los que venís trabajando y esta nueva tabla.</li>
<li>Uní los datos con joins. ¿Cuál es la mejor opción?</li>
</ol>
</div>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05_graficos.html" class="pagination-link  aria-label=" datos="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Graficado datos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07_funciones.html" class="pagination-link" aria-label="<span class='chapter-number'>8</span>&nbsp; <span class='chapter-title'>Funciones</span>">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Funciones</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>